#!/usr/bin/env node
// Derives the site-wide SEO bits from assets/translations.json, so adding a
// language or a whole new section is one JSON edit and nothing else:
//
//   1. sitemap.xml   every page of every section
//   2. robots.txt    allow-all plus the sitemap pointer
//   3. og:locale     one tag per page, from the entry's "locale" field
//
// Usage:
//   node scripts/sync-seo.mjs           # write files
//   node scripts/sync-seo.mjs --check   # exit 1 if anything would change

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, "..");
const HOST = "https://dontpastetheai.com";

function loadData() {
  const raw = readFileSync(
    join(REPO_ROOT, "assets", "translations.json"),
    "utf8",
  );
  const data = JSON.parse(raw);
  if (!Array.isArray(data.languages) || data.languages.length === 0) {
    throw new Error("translations.json: missing or empty 'languages' array");
  }
  return data;
}

// Every page on the site, as { file, url, locale }. The index of a section is
// served at the bare section URL, matching what the canonical tags say.
function allPages(data) {
  const pages = [];
  const add = (dir, entry) => {
    const prefix = dir ? `/${dir}/` : "/";
    const rel = dir ? `${dir}/${entry.file}` : entry.file;
    const url =
      entry.file === "index.html"
        ? `${HOST}${prefix}`
        : `${HOST}${prefix}${entry.file}`;
    pages.push({ file: rel, url, locale: entry.locale });
  };
  for (const lang of data.languages) {
    add("", lang);
    add("angry", lang);
  }
  for (const [name, entries] of Object.entries(data.pages ?? {})) {
    for (const entry of entries) add(name, entry);
  }
  return pages;
}

function buildSitemap(pages) {
  const urls = pages
    .map((p) => `  <url>\n    <loc>${p.url}</loc>\n  </url>`)
    .join("\n");
  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/sync-seo.mjs from assets/translations.json. Do not edit by hand. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>
`;
}

function buildRobots() {
  return `# Generated by scripts/sync-seo.mjs. Do not edit by hand.
User-agent: *
Allow: /

Sitemap: ${HOST}/sitemap.xml
`;
}

// og:locale is a single tag, so no marker block. Replace it when present,
// otherwise insert it right after og:type to keep the og group together.
function syncOgLocale(html, locale) {
  const tag = `<meta property="og:locale" content="${locale}">`;
  const existing = /[ \t]*<meta[^>]*property="og:locale"[^>]*>\n?/;
  if (existing.test(html)) {
    const indent = html.match(/([ \t]*)<meta[^>]*property="og:locale"/)[1];
    return html.replace(existing, `${indent}${tag}\n`);
  }
  const ogType = html.match(/([ \t]*)<meta[^>]*property="og:type"[^>]*>\n/);
  if (!ogType) return null;
  const indent = ogType[1];
  return html.replace(ogType[0], `${ogType[0]}${indent}${tag}\n`);
}

function main() {
  const check = process.argv.includes("--check");
  const data = loadData();
  const pages = allPages(data);

  const artifacts = [
    { path: "sitemap.xml", content: buildSitemap(pages) },
    { path: "robots.txt", content: buildRobots() },
  ];

  const changed = [];
  const missing = [];

  for (const a of artifacts) {
    const full = join(REPO_ROOT, a.path);
    const current = existsSync(full) ? readFileSync(full, "utf8") : null;
    if (current === a.content) continue;
    changed.push(a.path);
    if (!check) writeFileSync(full, a.content, "utf8");
  }

  for (const p of pages) {
    const full = join(REPO_ROOT, p.file);
    if (!existsSync(full)) {
      missing.push(p.file);
      continue;
    }
    if (!p.locale) {
      console.warn(`warn: no locale for ${p.file} in translations.json`);
      continue;
    }
    const original = readFileSync(full, "utf8");
    const updated = syncOgLocale(original, p.locale);
    if (updated === null) {
      console.warn(`warn: no og:type tag in ${p.file} (og:locale not added)`);
      continue;
    }
    if (updated === original) continue;
    changed.push(p.file);
    if (!check) writeFileSync(full, updated, "utf8");
  }

  for (const p of missing) console.warn(`warn: file not found: ${p}`);

  if (check) {
    if (changed.length) {
      console.log(`Out of sync: ${changed.length} file(s) would change:`);
      for (const p of changed) console.log(`  ${p}`);
      process.exit(1);
    }
    console.log(`SEO in sync (${pages.length} pages)`);
    return;
  }

  if (changed.length) {
    console.log(`Updated ${changed.length} file(s):`);
    for (const p of changed) console.log(`  ${p}`);
  } else {
    console.log(`SEO already up to date (${pages.length} pages)`);
  }
}

main();
